apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorizatsiya
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      labels:
        app: author
    spec:
      containers:
      - name: authorizatsiya
        image: k8s1.agrobank.uz:5000/authorizatisya:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "750Mi"
            cpu: "500m"
          requests:
            memory: "500Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: secretkey2        
---
apiVersion: v1
kind: Service
metadata:
  name: authorizatsiya
  namespace: default
spec:
  selector:
    app: author
  ports:
  - port: 5544
    targetPort: 5544
  externalIPs:
  - 192.168.10.73